/**
 * Plugin to generate a toc based on h tags and spit the output back using callbacks
 * @param callback function to be called
 * @param depth the depth of the heading
 * @param id generated by remark-slug
 */
export default function generateToc(
  callback: (toc: TOC) => {},
  depth: number = 2,
  id: boolean = false
);

export type TOC = {
  depth: number;
  value: string;
  id?: string;
};
